### ISSUE TITLE
Reset button styling

### ISSUE THREAD

**Issue by anthonygedeon** [feathericons/feathericons.com#551]
When playing with the customize tools, I noticed that the reset button is not really noticeable after changing the properties of the icons.

Styling the reset button to red will signify danger and become noticeable.

**Here's a screenshot of what I am talking about**

![image](https://user-images.githubusercontent.com/47023801/85169720-e72f4d80-b231-11ea-8906-201baeccc693.png)

**CSS Code** 

```CSS
.css-s700uk {
   --background-color: hsl(358, 91%, 45%); /* pick a suitable red color */
    box-shadow: inset 0 0 0 1px var(--background-color);
    background-color: var(--background-color);
}
```
